### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Avv22** [ITU-2019/AngleBasedOutlierDetection#8]
Thank you for this work. Can I run this method on my own dataset? Is it efficient to use this method in high dimensional multivariate data?

**Comment by Baunsgaard** [comment]
it is fairly efficient, but not recommended, since there are other more robust approaches that calculate outliers in multidimensional data.

if your datasets have really distinct clusters it is fine, but if the clusters lie in sequence with outliers in between it fails.

**Comment by Avv22** [comment]
@Baunsgaard . Thank you. What would you recommend to use in case of multivariate data with high dimension? You mean this method is not good if outliers are within clusters themselves?

**Comment by Baunsgaard** [comment]
the classification of an outlier using angles is that it is an outlier if a large number of hyperplane constructed by 3 points give small angles. 
you can imagine if points a and b are close while c is far away, the angle of a and b is large while c is small.
this clearly gives a classification of c being an outlier. 
now if we have more than one cluster, lets say cluster A and B, then all points in A and B is not outliers, but if we sample points from A and B then we are likely to encounter small angles. therefore the best application of this outlier technique is if you only have one spherical cluster.

**Comment by Avv22** [comment]
@Baunsgaard. Thank you. But in case of high dimensional vector that has at least 1000 dimension, if PCA was to be used, this would reduce the dimension, but still it would be large, say dimension is 20. In this case, do you think it's efficient to compare a set of vectors with 20 dimensions each to each other using angle-based approaches and if not, what would you recommend as alternative in case of high dimensional vector?

**Comment by Baunsgaard** [comment]
well the whole idea is that you wont have to use PCA with a angle based approach.
I don't remember if when we implemented this used hyperplanes to project multiple points to but this makes it fairly applicable.
but if you need to use PCA for following steps then this angle based is not recommended.
